apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}  # Chart.yaml: The 'name' scalar.
  name: {{ .Release.Name }} # Name of the local Helm release.
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Chart.AppVersion }}
          name: {{ .Release.Name }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            limits: 
              memory: "512Mi"
              cpu: "1"
          env:
            - name: DATABASE_HOST
              value: postgresql
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: password
            - name: DATABASE_NAME
              value: {{ .Values.postgresql.auth.database }}

