apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}  # Chart.yaml: The 'name' scalar.
  name: {{ .Release.Name }} # Name of the local Helm release.
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}  # Chart.yaml: The 'name' scalar.
  type: LoadBalancer
